"""initial migration

Revision ID: b17742926a7d
Revises: 
Create Date: 2025-03-29 19:21:18.773218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17742926a7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(), nullable=True),
    sa.Column('data_create_task', sa.String(), nullable=True),
    sa.Column('data_task', sa.String(), nullable=True),
    sa.Column('onoff', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_data_create_task'), 'tasks', ['data_create_task'], unique=False)
    op.create_index(op.f('ix_tasks_data_task'), 'tasks', ['data_task'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_onoff'), 'tasks', ['onoff'], unique=False)
    op.create_index(op.f('ix_tasks_task'), 'tasks', ['task'], unique=True)
    op.create_table('result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task', sa.String(), nullable=False),
    sa.Column('data_create_task', sa.String(), nullable=True),
    sa.Column('data_task', sa.String(), nullable=True),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('name_user', sa.String(), nullable=True),
    sa.Column('data_result_task', sa.String(), nullable=True),
    sa.Column('id_res', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['tasks.task'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_result_data_create_task'), 'result', ['data_create_task'], unique=False)
    op.create_index(op.f('ix_result_data_result_task'), 'result', ['data_result_task'], unique=False)
    op.create_index(op.f('ix_result_data_task'), 'result', ['data_task'], unique=False)
    op.create_index(op.f('ix_result_flag'), 'result', ['flag'], unique=False)
    op.create_index(op.f('ix_result_id'), 'result', ['id'], unique=False)
    op.create_index(op.f('ix_result_id_res'), 'result', ['id_res'], unique=False)
    op.create_index(op.f('ix_result_name_user'), 'result', ['name_user'], unique=False)
    op.create_index(op.f('ix_result_task'), 'result', ['task'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_result_task'), table_name='result')
    op.drop_index(op.f('ix_result_name_user'), table_name='result')
    op.drop_index(op.f('ix_result_id_res'), table_name='result')
    op.drop_index(op.f('ix_result_id'), table_name='result')
    op.drop_index(op.f('ix_result_flag'), table_name='result')
    op.drop_index(op.f('ix_result_data_task'), table_name='result')
    op.drop_index(op.f('ix_result_data_result_task'), table_name='result')
    op.drop_index(op.f('ix_result_data_create_task'), table_name='result')
    op.drop_table('result')
    op.drop_index(op.f('ix_tasks_task'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_onoff'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_data_task'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_data_create_task'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
